version: "3.8"

services:
  # ─── 🐘 DATABASE ─────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - presence

  # ─── 🚀 BACKEND EXPRESS + PRISMA ─────────────
  backend:
    image: ghcr.io/rino21/presence/staging/api:dev
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.presence-api.rule=Host(`api-presence-dev.local`)
    #   - traefik.http.services.presence-api.loadbalancer.server.port=3000
    ports:
      - "3000:3000"
    container_name: backend_container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - presence

  studio: 
    image: ghcr.io/rino21/presence/staging/api:dev
    command: sh -c "npx prisma studio --hostname 0.0.0.0 --port 5555"
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.presence-studio.rule=Host(`studio-presence-dev.local`)
    #   - traefik.http.services.presence-studio.loadbalancer.server.port=5555
    ports:
      - "5555:5555"
    container_name: backend_studio
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - presence
  # ─── 🌐 FRONTEND REACT + NGINX ─────────────
  frontend:
    image: ghcr.io/rino21/presence/staging/front:dev
    # labels:
    #     - traefik.enable=true
    #     - traefik.http.routers.presence-front.rule=Host(`front-presence-dev.local`)
    #     - traefik.http.services.presence-front.loadbalancer.server.port=80
    ports:
      - "80:80"
    container_name: frontend_container
    depends_on:
      - backend
    networks:
      - presence

volumes:
  pgdata:

networks:
  presence:
    external: true
    name: traefik_presence